name: auto_build
on:  workflow_dispatch
jobs: 
  build_project:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: View dir
        run: |
          cd HW-1/1
          rm -R build
          mkdir build 
          cd build 
          cmake -G "Ninja" .. 
          cmake  --build .         
